# Generated by Django 5.2.3 on 2025-07-05 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ativos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrada', models.DateField()),
                ('tipo', models.CharField(choices=[('C', 'Compra'), ('V', 'Venda')], max_length=1)),
                ('quantidade', models.PositiveIntegerField()),
                ('preco_entrada', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preco_saida', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('data_saida', models.DateField(blank=True, null=True)),
                ('opcao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ativos.opcao')),
            ],
        ),
    ]
