# Generated by Django 5.2.3 on 2025-06-28 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('setor', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Opcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('CALL', 'Call'), ('PUT', 'Put')], max_length=4)),
                ('strike', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vencimento', models.DateField()),
                ('ativo_subjacente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opcoes', to='ativos.acao')),
            ],
            options={
                'unique_together': {('ativo_subjacente', 'tipo', 'strike', 'vencimento')},
            },
        ),
    ]
